package com.sixu.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-03-14T20:18:10.716+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebServiceClient(name = "IHelloServiceImplService", 
                  wsdlLocation = "http://localhost:8080/spring-webservice/services/Hellows?wsdl",
                  targetNamespace = "http://webservice.sixu.com/") 
public class IHelloServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.sixu.com/", "IHelloServiceImplService");
    public final static QName IHelloServiceImplPort = new QName("http://webservice.sixu.com/", "IHelloServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/spring-webservice/services/Hellows?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(IHelloServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/spring-webservice/services/Hellows?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public IHelloServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public IHelloServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IHelloServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IHelloServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IHelloServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public IHelloServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName);
    }

    /**
     *
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "IHelloServiceImplPort")
    public IHelloService getIHelloServiceImplPort() {
        return super.getPort(IHelloServiceImplPort, IHelloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHelloService
     */
    @WebEndpoint(name = "IHelloServiceImplPort")
    public IHelloService getIHelloServiceImplPort(WebServiceFeature... features) {
        return super.getPort(IHelloServiceImplPort, IHelloService.class, features);
    }

}
