package com.sixu.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.2
 * 2016-03-14T20:18:10.706+08:00
 * Generated source version: 2.5.2
 * 
 */
@WebService(targetNamespace = "http://webservice.sixu.com/", name = "IHelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface IHelloService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://webservice.sixu.com/", className = "com.sixu.webservice.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://webservice.sixu.com/", className = "com.sixu.webservice.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
